-- This file was SUPPOSED TO BE @generated by Tarmac.
-- It's not working though
-- So all of this is manual, re-run Tarmac at own risk.
return {
	Texture = {
		Gamepass = {
			Icon = {
				AutoClick = "rbxassetid://12791265832",
				AutoHatch = "rbxassetid://12791265760",
				DoubleCash = "rbxassetid://12791265683",
				DoublePassiveCash = "rbxassetid://12791265615",
				Lucky = "rbxassetid://12791265539",
				SuperLucky = "rbxassetid://12791265456",
				TripleHatch = "rbxassetid://12791265386",
			},
			Tab = {
				Blue = "rbxassetid://12791271035",
				Green = "rbxassetid://12791270963",
				Purple = "rbxassetid://12791270812",
				Yellow = "rbxassetid://12791270666",
			},
		},
		Menu = {
			ExitButton = {
				Default = "rbxassetid://12791273858",
				Hovered = "rbxassetid://12791273783",
				Pressed = "rbxassetid://12791273711",
			},
			Index = {
				Default = "rbxassetid://12791275999",
				Hover = "rbxassetid://12791275816",
			},
			Pets = {
				Default = "rbxassetid://12791278863",
				Hover = "rbxassetid://12791278759",
			},
			Settings = {
				Default = "rbxassetid://12791279898",
				Hover = "rbxassetid://12791279857",
			},
			Shop = {
				Default = "rbxassetid://12791281461",
				Hover = "rbxassetid://12791281378",
			},
		},
	},
}
